default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: bos_eriko_data_development

test:
  <<: *default
  database: bos_eriko_data_test

production:
  <<: *default
  database: bos_eriko_data_production
  host: heroku