default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "db_user" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "db_password" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

development:
  <<: *default
  database: bos_eriko_data_development

test:
  <<: *default
  database: bos_eriko_data_test

production:
  <<: *default
  database: bos_eriko_data_production
  username: <%= ENV.fetch("DB_USERNAME") { "db_user" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "db_password" } %>
  host: heroku
